/* GAP-03 — DDL extraido do FATURA.GDB (Firebird 2.5, 192.168.0.6)
   em 03/09/2026 11:31 por scratchpad/extrai_ddl.py, somente leitura de rdb$*.
   Apenas as tabelas da secao 4.1 da ESPECIFICACAO.md. Fonte de tipos reais para RD-* e QRY-*. */

CREATE TABLE PESSOAS (
    PESSOA                       VARCHAR(10) CHARACTER SET NONE NOT NULL,
    NOME                         VARCHAR(50) CHARACTER SET NONE,
    CPF_CNPJ                     VARCHAR(14) CHARACTER SET NONE,
    ENDERECO                     VARCHAR(50) CHARACTER SET NONE,
    CEP                          VARCHAR(8) CHARACTER SET NONE,
    BAIRRO                       VARCHAR(40) CHARACTER SET NONE,
    CIDADE                       VARCHAR(40) CHARACTER SET NONE,
    ESTADO                       VARCHAR(2) CHARACTER SET NONE NOT NULL,
    TP_PESSOA                    VARCHAR(1) CHARACTER SET NONE,
    SEXO                         VARCHAR(1) CHARACTER SET NONE,
    STATUS                       VARCHAR(1) CHARACTER SET NONE DEFAULT 'A' NOT NULL,
    BANCO                        VARCHAR(4) CHARACTER SET NONE,
    AGENCIA                      VARCHAR(10) CHARACTER SET NONE,
    CONTA                        VARCHAR(20) CHARACTER SET NONE,
    FAVOR_CONTA                  VARCHAR(100) CHARACTER SET NONE,
    EMAIL                        VARCHAR(254) CHARACTER SET NONE,
    OBS                          VARCHAR(100) CHARACTER SET NONE,
    DT_CADASTRO                  DATE,
    EMITE_NF                     VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    ABREV                        VARCHAR(10) CHARACTER SET NONE,
    DDD1                         VARCHAR(2) CHARACTER SET NONE,
    TELEFONE1                    VARCHAR(9) CHARACTER SET NONE,
    DDD2                         VARCHAR(2) CHARACTER SET NONE,
    TELEFONE2                    VARCHAR(9) CHARACTER SET NONE,
    CONTATO                      VARCHAR(50) CHARACTER SET NONE,
    CEDENTE                      VARCHAR(2) CHARACTER SET NONE,
    DIA_VENCIMENTO               INTEGER,
    PRESTADOR                    VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    CONV_PRESTADOR               VARCHAR(10) CHARACTER SET NONE,
    COD_PRESTADOR                VARCHAR(30) CHARACTER SET NONE,
    OPTOU_SIMPLES                VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    COD_GERENTE                  VARCHAR(4) CHARACTER SET NONE DEFAULT '0001' NOT NULL,
    CHAVE_PIX                    VARCHAR(77) CHARACTER SET NONE,
    POSSUI_PORTAL                VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    ENDER_PORTAL                 VARCHAR(100) CHARACTER SET NONE,
    COD_GERENTE_EXTRA            VARCHAR(4) CHARACTER SET NONE
);
ALTER TABLE PESSOAS ADD CONSTRAINT PK_PESSOAS PRIMARY KEY (PESSOA);
CREATE INDEX PESSOAS_IDX1 ON PESSOAS (NOME);
CREATE INDEX PESSOAS_IDX2 ON PESSOAS (CPF_CNPJ);
CREATE INDEX PESSOAS_IDX3 ON PESSOAS (STATUS);
CREATE UNIQUE INDEX PK_PESSOAS ON PESSOAS (PESSOA);

CREATE TABLE FATURAS (
    FATURA                       INTEGER NOT NULL,
    TIPO_FAT                     VARCHAR(1) CHARACTER SET NONE NOT NULL,
    ADMINISTRADORA               VARCHAR(10) CHARACTER SET NONE NOT NULL,
    APOLICE                      VARCHAR(20) CHARACTER SET NONE NOT NULL,
    SEQ                          INTEGER NOT NULL,
    SEGURADORA                   VARCHAR(10) CHARACTER SET NONE NOT NULL,
    QTD_ITENS                    INTEGER,
    DATA_FAT                     DATE,
    CAPITAL_TOTAL                DECIMAL(18,2),
    PREMIO_BRUTO                 DECIMAL(18,2),
    DEVOLUCAO                    DECIMAL(18,2),
    ACRESCIMO                    DECIMAL(18,2),
    IOF                          DECIMAL(6,3),
    PREMIO_LIQ                   DECIMAL(18,2),
    BOLETA_REC                   DECIMAL(18,2),
    VALOR_QUITADO                DECIMAL(18,2),
    NOSSO_NUMERO                 VARCHAR(10) CHARACTER SET NONE,
    VENCIMENTO                   DATE,
    PARCELAS                     INTEGER,
    CORRETOR                     VARCHAR(10) CHARACTER SET NONE,
    COMISSAO                     DECIMAL(6,2),
    DESC_COMISSAO                DECIMAL(6,2),
    COMISSAO_LIQ                 DECIMAL(18,2),
    TIPO_COMISSAO                VARCHAR(10) CHARACTER SET NONE,
    VOUCHER                      VARCHAR(10) CHARACTER SET NONE,
    DATA_REPASSE                 DATE,
    BOLETA_QUITADA               VARCHAR(1) CHARACTER SET NONE,
    DT_BAIXA                     DATE,
    CORRETOR2                    VARCHAR(10) CHARACTER SET NONE,
    COMISSAO2                    DECIMAL(6,2),
    DESC_COMISSAO2               DECIMAL(6,2),
    COMISSAO_LIQ2                DECIMAL(18,2),
    TIPO_COMISSAO2               VARCHAR(10) CHARACTER SET NONE,
    STATUS                       VARCHAR(1) CHARACTER SET NONE DEFAULT 'A',
    TOTAL_SEG                    DECIMAL(18,2) DEFAULT 0,
    RAMO                         VARCHAR(1) CHARACTER SET NONE DEFAULT 'V',
    VALOR_BR_ASSIST              DECIMAL(18,2) DEFAULT 0,
    DT_INI_VIG                   DATE,
    DT_FIM_VIG                   DATE,
    DT_CANCEL                    DATE,
    OBS_CANCEL                   VARCHAR(100) CHARACTER SET NONE,
    OUT_FAT                      INTEGER,
    AJUSTES                      DECIMAL(16,2),
    CONTABILIZA                  VARCHAR(1) CHARACTER SET NONE DEFAULT 'S' NOT NULL,
    CEDENTE                      VARCHAR(2) CHARACTER SET NONE,
    ENDOSSO                      VARCHAR(20) CHARACTER SET NONE,
    SEQ_ENDOSSO                  INTEGER,
    FATURA_REAJUSTE              VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    USUARIO_CAD                  VARCHAR(20) CHARACTER SET NONE,
    TP_FATURA                    VARCHAR(1) CHARACTER SET NONE
);
ALTER TABLE FATURAS ADD CONSTRAINT FK_FATURAS_2 FOREIGN KEY (APOLICE, SEGURADORA, ADMINISTRADORA, SEQ) REFERENCES APOLICES /* via PK_APOLICES */ ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE FATURAS ADD CONSTRAINT FK_FATURAS_3 FOREIGN KEY (SEGURADORA) REFERENCES SEGURADORA /* via PK_SEGURADORA */ ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE FATURAS ADD CONSTRAINT PK_FATURAS PRIMARY KEY (FATURA, TIPO_FAT, ADMINISTRADORA, APOLICE, SEQ, SEGURADORA);
CREATE INDEX FATURAS_DATA_SEG ON FATURAS (DT_INI_VIG, SEGURADORA);
CREATE INDEX FATURAS_IDX1 ON FATURAS (FATURA);
CREATE INDEX FATURAS_IDX2 ON FATURAS (STATUS);
CREATE INDEX FATURAS_IDX3 ON FATURAS (DATA_FAT);
CREATE INDEX FATURAS_IDX4 ON FATURAS (RAMO);
CREATE INDEX FATURAS_IDX5 ON FATURAS (STATUS, DT_INI_VIG);
CREATE INDEX FATURAS_IDX6 ON FATURAS (FATURA, TIPO_FAT, PARCELAS);
CREATE INDEX FATURAS_IDX7 ON FATURAS (FATURA, TIPO_FAT);
CREATE INDEX FK_FATURAS_2 ON FATURAS (APOLICE, SEGURADORA, ADMINISTRADORA, SEQ);
CREATE INDEX FK_FATURAS_3 ON FATURAS (SEGURADORA);
CREATE UNIQUE INDEX PK_FATURAS ON FATURAS (FATURA, TIPO_FAT, ADMINISTRADORA, APOLICE, SEQ, SEGURADORA);

CREATE TABLE ENDOSSOS (
    COD_EST_END                  VARCHAR(2) CHARACTER SET NONE NOT NULL,
    COD_RAMO                     VARCHAR(2) CHARACTER SET NONE NOT NULL,
    COD_CAT                      VARCHAR(1) CHARACTER SET NONE NOT NULL,
    SEQUENCIAL                   INTEGER NOT NULL,
    ENDOSSO                      VARCHAR(11) CHARACTER SET NONE,
    ENDOSSO_ANT                  VARCHAR(11) CHARACTER SET NONE,
    DT_CRIACAO                   DATE,
    APOLICE                      VARCHAR(20) CHARACTER SET NONE,
    SEQ                          INTEGER,
    ADMINISTRADORA               VARCHAR(10) CHARACTER SET NONE,
    COD_SEGURADORA               VARCHAR(10) CHARACTER SET NONE,
    INICIO_VIG                   DATE,
    FINAL_VIG                    DATE,
    STATUS                       VARCHAR(1) CHARACTER SET NONE DEFAULT 'A' NOT NULL,
    DT_CANCEL                    DATE,
    RENOVADO                     VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    END_ANTERIOR                 VARCHAR(11) CHARACTER SET NONE,
    FATURADO                     VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    IMPORTADO                    VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    APOLICE_SEGURADORA           VARCHAR(20) CHARACTER SET NONE,
    IMPRESSO                     VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    ASSISTENCIA                  VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    COB_ESPECIAIS                VARCHAR(1) CHARACTER SET NONE,
    CODIGO_ASSIST_MONDIAL        VARCHAR(4) CHARACTER SET NONE
);
ALTER TABLE ENDOSSOS ADD CONSTRAINT FK_END_CAT FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA /* via PK_CATEGORIA */ ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ENDOSSOS ADD CONSTRAINT FK_END_ESTADO FOREIGN KEY (COD_EST_END) REFERENCES ESTADOS /* via UNQ1_ESTADOS */ ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ENDOSSOS ADD CONSTRAINT FK_END_RAMO FOREIGN KEY (COD_RAMO) REFERENCES RAMOS /* via PK_RAMOS */ ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ENDOSSOS ADD CONSTRAINT PK_ENDOSSOS PRIMARY KEY (COD_EST_END, COD_RAMO, COD_CAT, SEQUENCIAL);
ALTER TABLE ENDOSSOS ADD CONSTRAINT UNQ1_ENDOSSOS UNIQUE (ENDOSSO);
CREATE INDEX ENDOSSOS_APOLICE ON ENDOSSOS (APOLICE, SEQ, ADMINISTRADORA, COD_SEGURADORA);
CREATE INDEX ENDOSSOS_IDX1 ON ENDOSSOS (INICIO_VIG, STATUS);
CREATE INDEX ENDOSSOS_IDX2 ON ENDOSSOS (COD_CAT, IMPRESSO);
CREATE INDEX ENDOSSOS_IDX3 ON ENDOSSOS (STATUS);
CREATE INDEX ENDOSSOS_IDX4 ON ENDOSSOS (SEQUENCIAL);
CREATE INDEX ENDOSSOS_IDX5 ON ENDOSSOS (ADMINISTRADORA, COD_CAT, IMPRESSO);
CREATE INDEX ENDOSSOS_IDX6 ON ENDOSSOS (RENOVADO, STATUS);
CREATE INDEX ENDOSSOS_IDX7 ON ENDOSSOS (STATUS, FATURADO);
CREATE INDEX ENDOSSOS_IDX8 ON ENDOSSOS (STATUS, INICIO_VIG);
CREATE INDEX FK_END_CAT ON ENDOSSOS (COD_CAT);
CREATE INDEX FK_END_ESTADO ON ENDOSSOS (COD_EST_END);
CREATE INDEX FK_END_RAMO ON ENDOSSOS (COD_RAMO);
CREATE UNIQUE INDEX PK_ENDOSSOS ON ENDOSSOS (COD_EST_END, COD_RAMO, COD_CAT, SEQUENCIAL);
CREATE UNIQUE INDEX UNQ1_ENDOSSOS ON ENDOSSOS (ENDOSSO);

CREATE TABLE SEGURADOS_INC (
    ENDOSSO                      VARCHAR(11) CHARACTER SET NONE NOT NULL,
    APOLICE                      VARCHAR(20) CHARACTER SET NONE NOT NULL,
    SEQ                          INTEGER NOT NULL,
    ADMINISTRADORA               VARCHAR(10) CHARACTER SET NONE NOT NULL,
    COD_SEGURADORA               VARCHAR(10) CHARACTER SET NONE NOT NULL,
    FATURA                       INTEGER,
    TIPO_FAT                     VARCHAR(1) CHARACTER SET NONE,
    APOLICE_SEGURADORA           VARCHAR(20) CHARACTER SET NONE,
    INICIO_VIG                   DATE,
    FINAL_VIG                    DATE,
    STATUS_SEG                   VARCHAR(1) CHARACTER SET NONE,
    CERTIFICADO                  VARCHAR(30) CHARACTER SET NONE NOT NULL,
    NOME                         VARCHAR(50) CHARACTER SET NONE,
    CPF_CNPJ                     VARCHAR(14) CHARACTER SET NONE,
    ENDERECO                     VARCHAR(90) CHARACTER SET NONE NOT NULL,
    CEP                          VARCHAR(8) CHARACTER SET NONE,
    BAIRRO                       VARCHAR(40) CHARACTER SET NONE,
    CIDADE                       VARCHAR(40) CHARACTER SET NONE,
    UF                           VARCHAR(2) CHARACTER SET NONE,
    UNIDADE                      VARCHAR(35) CHARACTER SET NONE,
    CAT_IMOVEL                   VARCHAR(10) CHARACTER SET NONE,
    TIPO_CATEGORIA               VARCHAR(1) CHARACTER SET NONE,
    ATIVIDADE                    VARCHAR(25) CHARACTER SET NONE,
    TX_ATIVIDADE                 DECIMAL(16,10),
    PREMIO                       DECIMAL(16,2),
    INC_CONTEUDO                 DECIMAL(16,2),
    INC_PREDIO                   DECIMAL(16,2),
    ALUGUEL                      DECIMAL(16,2),
    DT_IMPORTACAO                DATE,
    USU_IMPORTACAO               VARCHAR(10) CHARACTER SET NONE,
    DT_CANCEL                    DATE,
    IMPRESSO                     VARCHAR(1) CHARACTER SET NONE DEFAULT 'N' NOT NULL,
    DT_IMPRESSAO                 DATE,
    USU_IMPRESSAO                VARCHAR(10) CHARACTER SET NONE,
    REFERENCIA                   VARCHAR(7) CHARACTER SET NONE,
    NOME_COND                    VARCHAR(50) CHARACTER SET NONE,
    METROS2                      DECIMAL(8,2),
    VALOR_DO_ALUGUEL             DECIMAL(15,2),
    COD_PRODUTO                  VARCHAR(4) CHARACTER SET NONE,
    TAXA_SISTEMA                 DECIMAL(16,10),
    SISTEMA                      VARCHAR(10) CHARACTER SET NONE,
    CODIGO_PEDIDO_PORT           INTEGER,
    ENVIO_SEGURADORA             DATE,
    LINK_CERTIFICADO_AWS         VARCHAR(200) CHARACTER SET NONE,
    DT_CRIA_LINK                 DATE,
    ID_PEDIDO_PORTAL             VARCHAR(10) CHARACTER SET NONE,
    ID_CONTROLE_ENVIO_PORTAL     INTEGER,
    CODIGO_PEDIDO_PORTAL         INTEGER,
    NASCIMENTO                   DATE,
    SEXO                         VARCHAR(1) CHARACTER SET NONE,
    CERT_BRADESCO                INTEGER
);
ALTER TABLE SEGURADOS_INC ADD CONSTRAINT FK_SEGURADOS_APOLICES FOREIGN KEY (APOLICE, COD_SEGURADORA, ADMINISTRADORA, SEQ) REFERENCES APOLICES /* via PK_APOLICES */ ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE SEGURADOS_INC ADD CONSTRAINT FK_SEGURADOS_ENDOSSO FOREIGN KEY (ENDOSSO) REFERENCES ENDOSSOS /* via UNQ1_ENDOSSOS */ ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE SEGURADOS_INC ADD CONSTRAINT FK_SEGURADOS_TP_CATEGORIA FOREIGN KEY (TIPO_CATEGORIA) REFERENCES TIPO_CATEGORIA /* via PK_TIPO_CATEGORIA */ ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE SEGURADOS_INC ADD CONSTRAINT PK_SEGURADOS_INC PRIMARY KEY (ENDOSSO, CERTIFICADO);
CREATE INDEX FK_SEGURADOS_APOLICES ON SEGURADOS_INC (APOLICE, COD_SEGURADORA, ADMINISTRADORA, SEQ);
CREATE INDEX FK_SEGURADOS_ENDOSSO ON SEGURADOS_INC (ENDOSSO);
CREATE INDEX FK_SEGURADOS_TP_CATEGORIA ON SEGURADOS_INC (TIPO_CATEGORIA);
CREATE UNIQUE INDEX PK_SEGURADOS_INC ON SEGURADOS_INC (ENDOSSO, CERTIFICADO);
CREATE INDEX SEGURADOS_INC_FATURA ON SEGURADOS_INC (FATURA, TIPO_FAT);
CREATE INDEX SEGURADOS_INC_IDX1 ON SEGURADOS_INC (ENDOSSO);
CREATE INDEX SEGURADOS_INC_IDX2 ON SEGURADOS_INC (ENDERECO);
CREATE INDEX SEGURADOS_INC_IDX3 ON SEGURADOS_INC (NOME, STATUS_SEG);
CREATE INDEX SEGURADOS_INC_IDX4 ON SEGURADOS_INC (INICIO_VIG);
CREATE INDEX SEGURADOS_INC_IDX5 ON SEGURADOS_INC (ADMINISTRADORA, CERTIFICADO);
CREATE INDEX SEGURADOS_INC_IDX6 ON SEGURADOS_INC (CPF_CNPJ);
CREATE INDEX SEGURADOS_INC_IDX7 ON SEGURADOS_INC (STATUS_SEG, INICIO_VIG);
CREATE INDEX SEGURADOS_INC_IDX8 ON SEGURADOS_INC (CODIGO_PEDIDO_PORT);

CREATE TABLE APOLICE_SEGURADORA (
    CODIGO                       INTEGER NOT NULL,
    APOLICE                      VARCHAR(30) CHARACTER SET NONE NOT NULL,
    APOLICE_SEGURADORA           VARCHAR(30) CHARACTER SET NONE NOT NULL,
    COD_SEGURADORA               VARCHAR(10) CHARACTER SET NONE NOT NULL,
    PROC_SUSEP                   VARCHAR(30) CHARACTER SET NONE,
    STATUS                       VARCHAR(1) CHARACTER SET NONE DEFAULT 'A' NOT NULL
);
ALTER TABLE APOLICE_SEGURADORA ADD CONSTRAINT PK_APOLICE_SEGURADORA PRIMARY KEY (CODIGO);
CREATE UNIQUE INDEX PK_APOLICE_SEGURADORA ON APOLICE_SEGURADORA (CODIGO);

CREATE TABLE SEGURADOS_INC_COB_AUX (
    ENDOSSO                      VARCHAR(11) CHARACTER SET NONE NOT NULL,
    CERTIFICADO                  VARCHAR(30) CHARACTER SET NONE NOT NULL,
    FATURA                       INTEGER,
    RC                           DECIMAL(16,2),
    VENDAVAL                     DECIMAL(16,2),
    DANOS_ELETRICOS              DECIMAL(16,2),
    STATUS                       VARCHAR(1) CHARACTER SET NONE DEFAULT 'A' NOT NULL,
    PREMIO                       DECIMAL(16,2),
    LINHA_BRANCA                 VARCHAR(1) CHARACTER SET NONE DEFAULT 'N',
    QUEBRA_VIDRO                 DECIMAL(16,2),
    RESP_CIVIL                   DECIMAL(16,2),
    RUP_ENCANAMENTO              DECIMAL(16,2),
    RUP_ENC_TER                  DECIMAL(16,2),
    ACIDENTE_PESSOAL             DECIMAL(16,2),
    NASCIMENTO                   DATE,
    SEXO                         VARCHAR(1) CHARACTER SET NONE,
    CERT_BRADESCO                INTEGER
);
ALTER TABLE SEGURADOS_INC_COB_AUX ADD CONSTRAINT PK_SEGURADOS_INC_COB_AUX PRIMARY KEY (ENDOSSO, CERTIFICADO);
CREATE UNIQUE INDEX PK_SEGURADOS_INC_COB_AUX ON SEGURADOS_INC_COB_AUX (ENDOSSO, CERTIFICADO);
CREATE INDEX SEGURADOS_INC_COB_AUX_IDX1 ON SEGURADOS_INC_COB_AUX (FATURA);
